version: '2'

services:

  nexus:
    image: sonatype/nexus3
    volumes:
        - nexus3-data:/nexus-data
    environment:
        - "INSTALL4J_ADD_VM_PARAMS=${INSTALL4J_ADD_VM_PARAMS}"
        - "NEXUS_CONTEXT=${NEXUS_CONTEXT}"
    labels:
      io.rancher.container.hostname_override: container_name

volumes:
    nexus3-data:
        driver: rancher-nfs
        driver_opts:
            onRemove: retain
            exportBase: /nexus3-data
