version: '2'

catalog:
    name: "Zammad"
    version: "2.2.0-14"
    description: "Zammad is a web based open source helpdesk/customer support system"
    uuid: zammad-1
    minimum_rancher_version: v1.2.0
    questions:
      - variable: "IMAGE_REPO"
        label: "Repository where the images should be pulled from. "
        description: |
            Leave the default, if you don't have your own images built.
        default: zammad/zammad-docker-compose
        required: true
        type: string

services:

  zammad-backup:
    scale: 1
    start_on_create: true

  zammad-elasticsearch:
    scale: 1
    start_on_create: true

  zammad-init:
    scale: 1
    start_on_create: true

  zammad-memcached:
    scale: 1
    start_on_create: true

  zammad-nginx:
    scale: 1
    start_on_create: true

  zammad-postgresql:
    scale: 1
    start_on_create: true

  zammad-scheduler:
    scale: 1
    start_on_create: true

  zammad-railsserver:
    scale: 1
    start_on_create: true

  zammad-websocket:
    scale: 1
    start_on_create: true
